import type { SopDoc } from './types';

const TODAY = new Date().toISOString().slice(0, 10);

export const DEFAULT_SOPS: SopDoc[] = [
  {
    id: 'warehouse',
    title: '跨境电商仓储入库标准作业程序',
    desc: '适用于跨境电商海外仓货物入库验收、上架的标准操作流程，确保库存准确性与作业效率。',
    type: 'inbound',
    owner: '仓储主管 / 入库组长',
    duration: '30-45 分钟 / 批次',
    scenario: 'FBA 头程 / 自发货物',
    version: 'V2.1',
    status: '已启用',
    updatedAt: TODAY,
    steps: [
      {
        id: 1,
        type: 'action',
        title: '预约到货确认',
        content:
          '接收供应商 / 货代的到货预约，确认预计到达时间、货物类型、数量及特殊要求（如温控、易碎品）。在 WMS 系统中创建预收货单（ASN）。',
        role: '入库专员',
        time: '10 分钟',
        tools: ['WMS 系统', '通讯软件'],
        risks: ['预约信息不准确导致库位准备不足'],
        controls: ['建立预约审核机制，要求提前 24 小时预约'],
        checklist: ['确认供应商信息', '核对 SKU 清单', '检查特殊存储要求'],
      },
      {
        id: 2,
        type: 'action',
        title: '月台调度与卸货',
        content:
          '根据货物类型分配合适的月台（常温 / 冷链 / 大件）。指挥叉车 / 人工卸货，核对封条完整性，检查外包装破损情况。',
        role: '现场主管',
        time: '15-20 分钟',
        tools: ['叉车', 'PDA', '月台调度系统'],
        risks: ['卸货顺序混乱，交叉污染'],
        controls: ['按货物类型分区卸货，冷链优先'],
        checklist: ['检查车辆封条', '拍照留存', '核对运单号'],
      },
      {
        id: 3,
        type: 'decision',
        title: '外包装初检',
        content:
          '检查货物外包装是否完好，有无明显破损、水渍、变形。如发现问题，进入异常处理流程。',
        condition: '包装是否完好？',
        yesNext: 4,
        noNext: 7,
        yesSubsteps: [
          '在系统中标记「包装合格」',
          '将货物流转至数量清点区',
          '通知入库专员进入下一环节',
        ],
        noSubsteps: [
          '现场拍照留证，多角度记录破损情况',
          '在 WMS 中创建异常工单，标记问题类型',
          '通知采购与承运方，暂停入库',
        ],
        role: '质检员',
        time: '5 分钟',
      },
      {
        id: 4,
        type: 'action',
        title: '数量清点与条码扫描',
        content:
          '使用 PDA 扫描货物条码，核对实物数量与 ASN 是否一致。对无条码货物进行临时编码贴标。记录差异并拍照。',
        role: '入库专员',
        time: '15 分钟',
        tools: ['PDA 手持终端', '条码打印机'],
        risks: ['扫描错误导致库存差异'],
        controls: ['双人复核机制，扫描后系统自动比对'],
        checklist: ['扫描每箱条码', '核对系统数量', '标记异常箱'],
      },
      {
        id: 5,
        type: 'decision',
        title: '数量一致性检查',
        content: '系统比对实际收货数量与预约数量差异是否在允许范围内（±2%）。',
        condition: '数量差异是否在允许范围？',
        yesNext: 6,
        noNext: 8,
        yesSubsteps: [
          '系统自动过账 ASN 单据',
          '将货物流转至质检抽检环节',
          '推送到账通知给采购与财务',
        ],
        noSubsteps: [
          '冻结 ASN 单据，禁止后续过账',
          '双人现场复盘、拍照核实实际差异',
          '登记差异说明并推送异常审批流',
        ],
        role: '系统',
        time: '实时',
      },
      {
        id: 6,
        type: 'action',
        title: '质量抽检与上架',
        content:
          '按 AQL 标准进行开箱抽检（一般检验水平 II）。合格货物按库位分配规则上架，更新库存状态为「可用」。',
        role: '质检员 / 上架员',
        time: '20 分钟',
        tools: ['质检工具包', '叉车', '库位标签'],
        risks: ['上架库位错误导致拣货效率低'],
        controls: ['系统推荐库位，上架后扫描库位码确认'],
        checklist: ['按 AQL 标准抽检', '检查商品质量', '扫描确认库位'],
      },
      {
        id: 7,
        type: 'action',
        title: '异常包装处理',
        content:
          '隔离破损货物，拍照记录，通知供应商 / 货代。填写《货损报告》，根据协商结果进行拒收或暂存待处理。',
        role: '异常处理专员',
        time: '20 分钟',
        tools: ['相机', '异常处理单'],
        risks: ['责任界定不清'],
        controls: ['全程视频监控，多方签字确认'],
        checklist: ['隔离异常货物', '拍照存档', '通知相关方'],
      },
      {
        id: 8,
        type: 'action',
        title: '数量差异处理',
        content:
          '暂停入库，联系供应商确认实际发货数量。如属供应商少发，按实际数量入库并标记差异；如属多发，暂存待指令。',
        role: '入库主管',
        time: '30 分钟',
        tools: ['通讯设备', '差异调整单'],
        risks: ['私自调整库存导致账实不符'],
        controls: ['所有调整需主管审批并留痕'],
        checklist: ['联系供应商', '确认差异原因', '审批调整单'],
      },
    ],
  },
  {
    id: 'delivery',
    title: '末端配送标准作业程序',
    desc: '适用于最后一公里配送及客户签收流程，覆盖装车、在途、签收三阶段管控。',
    type: 'transport',
    owner: '配送站长',
    duration: '按线路而定',
    scenario: 'B2C / C2C 末端',
    version: 'V1.4',
    status: '已启用',
    updatedAt: TODAY,
    steps: [
      {
        id: 1,
        type: 'action',
        title: '装车扫描与路线确认',
        content:
          '配送员扫描待配送包裹，确认装车顺序（先送后装）。检查车辆状态，确认配送路线优化结果。',
        role: '配送员',
        time: '15 分钟',
        tools: ['配送 APP', 'PDA', '车辆'],
        checklist: ['扫描全部包裹', '确认路线', '检查车辆油量 / 电量'],
      },
      {
        id: 2,
        type: 'action',
        title: '在途配送与异常上报',
        content:
          '按优化路线配送，途中如遇交通堵塞、车辆故障等异常，及时通过 APP 上报并申请路线调整。',
        role: '配送员',
        time: '按路线而定',
        tools: ['配送 APP', '导航软件'],
        checklist: ['保持 APP 在线', '遵守交通规则', '异常即时上报'],
      },
      {
        id: 3,
        type: 'action',
        title: '客户签收与回执',
        content:
          '上门派送，请客户验视外包装后签收。代收 / 自提柜需短信告知客户取件码。',
        role: '配送员',
        time: '3 分钟 / 件',
        tools: ['手持终端', '签收 APP'],
        checklist: ['核对收件人', '客户验视', '拍照留存签收凭证'],
      },
    ],
  },
  {
    id: 'returns',
    title: '退货处理 SOP',
    desc: '客户退货验收、检测、二次上架或销毁的完整闭环流程。',
    type: 'exception',
    owner: '逆向物流主管',
    duration: '20-60 分钟 / 单',
    scenario: '电商退货 / 售后换货',
    version: 'V1.2',
    status: '已启用',
    updatedAt: TODAY,
    steps: [
      {
        id: 1,
        type: 'action',
        title: '退货接收与单据核对',
        content:
          '接收退货包裹，核对退货申请单（RMA）与实物是否一致，扫描入库为「待检」状态。',
        role: '退货专员',
        time: '10 分钟',
        tools: ['RMA 系统', 'PDA'],
        checklist: ['核对 RMA 编号', '检查包裹完整性', '系统登记入库'],
      },
      {
        id: 2,
        type: 'decision',
        title: '商品状态评估',
        content: '依据外观、功能、附件三个维度判定是否可二次销售。',
        condition: '商品是否可二次销售？',
        yesNext: 3,
        noNext: 4,
        role: '质检员',
        time: '5 分钟',
      },
      {
        id: 3,
        type: 'action',
        title: '二次上架',
        content:
          '清洁、重新包装后上架到可售库位，更新库存状态。如属临期商品则标记预警。',
        role: '上架员',
        time: '10 分钟',
        tools: ['清洁工具', '包装耗材'],
        checklist: ['外观清洁', '重新包装', '扫描上架'],
      },
      {
        id: 4,
        type: 'action',
        title: '报废 / 退供应商',
        content:
          '无法二次销售的商品按报废流程处理或退回供应商，全程拍照留档并走审批。',
        role: '逆向物流主管',
        time: '20 分钟',
        tools: ['报废申请单'],
        risks: ['报废价值核算不准'],
        controls: ['按 SKU 标准成本核算 + 主管复核'],
        checklist: ['填写报废单', '主管审批', '财务备案'],
      },
    ],
  },
  {
    id: 'exception',
    title: '物流异常处理 SOP',
    desc: '覆盖运输破损、丢件、错发、延误四类常见异常的标准化响应、定责与赔付闭环。',
    type: 'exception',
    owner: '客服 & 异常处理组',
    duration: '2 小时内首响 / 24 小时闭环',
    scenario: '快递 / 干线 / 同城配',
    version: 'V1.1',
    status: '已启用',
    updatedAt: TODAY,
    steps: [
      {
        id: 1,
        type: 'action',
        title: '异常工单接入与登记',
        content:
          '客户通过电话 / 客服平台 / 商家后台反馈异常，客服按"运单号 + 异常类型 + 现场照片"快速建单，自动派单至异常处理组。',
        role: '客服',
        time: '5 分钟',
        tools: ['客服系统', '异常工单平台'],
        risks: ['客户信息不全 / 异常类型误判'],
        controls: ['工单必填字段 + 现场拍照模板提示'],
        checklist: [
          '运单号已核验',
          '异常类型已选择（破损/丢件/错发/延误）',
          '客户联系方式确认',
          '现场照片已上传',
        ],
        images: [],
      },
      {
        id: 2,
        type: 'decision',
        title: '异常类型分流',
        content:
          '系统按异常类型自动分流：破损 / 丢件 → 仓干配溯源；错发 → 拣货复核；延误 → 干线调度。',
        condition: '异常类型是否为「破损 / 丢件」？',
        yesNext: 3,
        noNext: 4,
        role: '系统',
        time: '实时',
      },
      {
        id: 3,
        type: 'action',
        title: '破损 / 丢件溯源调查',
        content:
          '调取运单全链路扫描记录、监控视频、签收照片。运输破损要求承运商出具《货损证明》；丢件需在 48 小时内提供承运商查件回执。',
        role: '异常处理专员',
        time: '2-8 小时',
        tools: ['TMS', '监控平台', '承运商接口'],
        risks: ['证据链不完整导致责任无法划分'],
        controls: ['关键节点（装车 / 中转 / 派送）必须有扫描或影像'],
        checklist: [
          '运单全链路记录已调取',
          '监控视频已留存',
          '承运商证明已索取',
          '货损照片清晰可辨',
        ],
        images: [],
      },
      {
        id: 4,
        type: 'action',
        title: '错发 / 延误现场核查',
        content:
          '错发：核对拣货 / 复核 / 出库扫描日志，判定是否人为差错。延误：核对承运商承运时效与异常报备记录，确认是否属于免责事由（恶劣天气 / 不可抗力）。',
        role: '运营专员',
        time: '1-4 小时',
        tools: ['WMS', 'TMS', '天气预报 API'],
        risks: ['人为差错被掩盖 / 免责事由误判'],
        controls: ['系统日志只读不可改 + 主管二次审核'],
        checklist: [
          '拣货 / 复核日志已核对',
          '承运商时效记录已比对',
          '免责事由有官方依据（如气象局）',
        ],
        images: [],
      },
      {
        id: 5,
        type: 'decision',
        title: '是否需要赔付？',
        content:
          '根据调查结论判定责任方：承运商责任 → 走承运商赔付；本方责任 → 启动内部赔付；客户 / 不可抗力 → 协商解决。',
        condition: '是否承运商 / 本方责任？',
        yesNext: 6,
        noNext: 7,
        role: '异常处理主管',
        time: '30 分钟',
      },
      {
        id: 6,
        type: 'action',
        title: '赔付方案与执行',
        content:
          '按《赔付标准表》计算金额（商品价值 + 运费）。承运商责任由财务追偿，本方责任在 24 小时内向客户完成退款 / 重发。',
        role: '财务 & 异常处理',
        time: '1-3 工作日',
        tools: ['财务系统', '赔付审批流'],
        risks: ['超标赔付 / 重复赔付'],
        controls: ['金额 ≥ 1000 元需总监审批 + 系统幂等校验'],
        checklist: [
          '赔付金额按标准计算',
          '审批流已走完',
          '客户已书面确认方案',
          '赔付凭证存档',
        ],
        images: [],
      },
      {
        id: 7,
        type: 'action',
        title: '客户安抚与协商',
        content:
          '客户责任 / 不可抗力情况下，由客服主管以共情话术安抚，必要时提供优惠券作为补偿。形成《非赔付沟通记录》存档。',
        role: '客服主管',
        time: '20 分钟',
        tools: ['客服平台', '优惠券中心'],
        risks: ['客户投诉升级到平台 / 监管'],
        controls: ['主管首响 + 1 小时回访'],
        checklist: ['沟通录音已存档', '补偿方案客户确认', '舆情监控已挂载'],
        images: [],
      },
      {
        id: 8,
        type: 'action',
        title: '复盘归档与防呆',
        content:
          '每月末汇总异常工单，按"频次 × 金额 × 影响"排序，TOP3 异常项纳入下月改进议题，更新 SOP 或培训。',
        role: '运营经理',
        time: '4 小时 / 月',
        tools: ['BI 报表', 'SOP 知识库'],
        risks: ['同类异常反复发生'],
        controls: ['改进项责任人 + 截止日 + 复核机制'],
        checklist: ['当月异常数据已汇总', 'TOP3 改进项已下发', 'SOP 已迭代版本'],
        images: [],
      },
    ],
  },
];

export const TEMPLATE_LIB: Array<{
  id: string;
  emoji: string;
  name: string;
  desc: string;
  generate: () => SopDoc;
}> = [
  {
    id: 'cold-chain',
    emoji: '❄️',
    name: '冷链物流 SOP',
    desc: '温度监控与异常处理',
    generate: () => ({
      id: 'tpl_cold_' + Date.now(),
      title: '冷链物流温控 SOP',
      desc: '覆盖冷链货物从装车到交付的全程温控与异常应急流程。',
      type: 'transport',
      owner: '冷链主管',
      duration: '按线路 / 全程在途',
      scenario: '生鲜 / 医药冷链',
      version: 'V1.0',
      status: '草稿',
      updatedAt: TODAY,
      steps: [
        {
          id: 1,
          type: 'action',
          title: '冷藏车预冷与检查',
          content:
            '装车前提前 30 分钟预冷至目标温度，检查制冷机组、温度记录仪、保温门密封性。',
          role: '冷链司机',
          time: '30 分钟',
          tools: ['温度记录仪', '冷藏车'],
          risks: ['预冷不到位导致出库即升温'],
          controls: ['系统强制记录预冷起始时间与温度'],
          checklist: ['制冷机组自检', '温度达到设定值', '门封完好'],
        },
        {
          id: 2,
          type: 'action',
          title: '在途温度实时监控',
          content:
            '全程 GPS + 温湿度数据上传中控平台，每 5 分钟一次。异常温度自动告警。',
          role: '中控调度',
          time: '在途持续',
          tools: ['冷链中控平台', 'IoT 温湿度传感器'],
          checklist: ['监控数据连续', '告警阈值正常'],
        },
        {
          id: 3,
          type: 'decision',
          title: '温度是否超阈值？',
          content: '判定在途温度是否突破设定阈值（生鲜 0-4℃ / 医药 2-8℃）。',
          condition: '温度是否在阈值内？',
          yesNext: 4,
          noNext: 5,
          role: '中控调度',
          time: '实时',
        },
        {
          id: 4,
          type: 'action',
          title: '正常交付',
          content: '按计划送达客户，打印温度全程曲线交付客户签收。',
          role: '冷链司机',
          time: '15 分钟',
          tools: ['温度曲线打印机'],
          checklist: ['客户验温', '签收并存档曲线'],
        },
        {
          id: 5,
          type: 'action',
          title: '温度异常应急',
          content:
            '立即就近转运到备用冷库或调度备用车辆，全程拍照与温度截图存档，通知客户与销售方协商。',
          role: '冷链主管',
          time: '30 分钟',
          tools: ['应急冷库', '通讯设备'],
          risks: ['货物变质或法规风险'],
          controls: ['应急 SOP + 保险理赔通道'],
          checklist: ['启动应急车辆', '截图取证', '客户告知'],
        },
      ],
    }),
  },
  {
    id: 'cross-border',
    emoji: '🌐',
    name: '跨境清关流程',
    desc: '报关报检标准程序',
    generate: () => ({
      id: 'tpl_border_' + Date.now(),
      title: '跨境进口清关 SOP',
      desc: '海运 / 空运进口货物的报关、报检、放行、提货全流程标准。',
      type: 'inbound',
      owner: '关务主管',
      duration: '1-3 工作日',
      scenario: '一般贸易 / 跨境电商保税',
      version: 'V1.0',
      status: '草稿',
      updatedAt: TODAY,
      steps: [
        {
          id: 1,
          type: 'action',
          title: '单据预审与归类',
          content:
            '收到提单 / 运单 / 发票 / 装箱单，预审一致性，完成 HS 编码归类。',
          role: '关务专员',
          time: '60 分钟',
          tools: ['单一窗口', '归类知识库'],
          checklist: ['提单 / 发票一致', 'HS 编码确认'],
        },
        {
          id: 2,
          type: 'action',
          title: '电子申报',
          content: '通过单一窗口录入报关报检数据，提交海关系统。',
          role: '关务专员',
          time: '30 分钟',
          tools: ['单一窗口', 'EDI'],
          checklist: ['申报字段完整', '回执已获取'],
        },
        {
          id: 3,
          type: 'decision',
          title: '是否查验？',
          content: '海关系统返回放行 / 查验指令。',
          condition: '是否查验？',
          yesNext: 4,
          noNext: 5,
          role: '关务专员',
          time: '实时',
        },
        {
          id: 4,
          type: 'action',
          title: '配合查验',
          content: '约时间到指定查验区域配合海关开箱查验，完成后等待放行。',
          role: '关务专员',
          time: '2-4 小时',
          tools: ['查验联系单'],
          checklist: ['现场到位', '查验照片留档'],
        },
        {
          id: 5,
          type: 'action',
          title: '缴税与放行提货',
          content: '电子缴税完成后系统放行，安排车辆到港 / 机场提货。',
          role: '关务专员 / 提货司机',
          time: '60-180 分钟',
          tools: ['电子缴税', '提货单'],
          checklist: ['税单到位', '提货单完整'],
        },
      ],
    }),
  },
];
